### ISSUE TITLE
MathSender Unit tests are failing - incomplete guide

### ISSUE THREAD

**Issue by weaselslider** [fprime-community/fprime-tutorial-math-component#26] opened 2024-02-09 04:48 UTC
in the writing-unit-tests part of the guide, the stub is not fully completed. the Tester needs to be completed as follows

void MathSenderTester ::
    from_mathOpOut_handler(
        NATIVE_INT_TYPE portNum,
        F32 val1,
        const MathModule::MathOp& op,
        F32 val2
    )
  {
    this->pushFromPortEntry_mathOpOut(val1, op, val2);
  }

this results in errors like so.
![ux8z66qXN6](https://github.com/fprime-community/fprime-tutorial-math-component/assets/25572804/a307b59e-1d85-411c-8839-35eb2aac72a5)

this is done correctly in the files provided, in Components/MathSender/test/ut/MathSenderTester.cpp , but the guide does not provide any mention to change the provided stub from //TODO
a mention to complete this function in writing-unit-tests-2.md would be nice.

Thanks to Caleb Schaefer for figuring this one out.

**Comment by thomas-bc** [comment] 2024-03-13 23:17
Thank you for reporting this - this is due to an oversight from us when we migrated from the old Python Autocoders for UTs towards FPP. We will ship a fix for next release, in the meantime I'll keep this issue open and renamed it so people can see the workaround.

**Comment by bocchino** [comment] 2024-04-09 22:48
After merging https://github.com/fprime-community/fpp/pull/401, the procedure for writing these handler functions will change.
1. The code for pushing data on the history will be in the auto-generated base class handler. If you want this default behavior, you will not need to do anything. The code will be there.
2. If you want more specific behavior, you can override the default implementation by adding an overriding function to the derived class.

Once FPP is updated, we should update the math component tutorial to match this behavior.

**Comment by thomas-bc** [comment] 2024-04-26 18:07
I have confirmed that the newest version of FPP fixes the issue. I did not notice things in the tutorial that need rewording with the change in FPP behavior, it should be transparent to the user at this point.

We will keep this issue open until the next release, as it can still pop up.
The fix is to run
```
pip install -U fprime-fpp==2.1.0a9
```

prior to running through the UT section.

**Comment by thomas-bc** [comment] 2024-10-16 17:43
Fixed in v3.5.0 release

**Closed by thomas-bc** 2024-10-16 17:43 UTC
Labels: bug
